# Don't change this
config-version: 1.0

# Automatically check for updates on launch
check-for-updates: true

# Type of database to use, choose SQLITE for a local database and MYSQL if you use a MYSQL database
database-type: SQLITE

# This will only be used if you use MYSQL as database-type
host: localhost
port: 3306
database: database
username: username
password: password
table-prefix: 'ref_'

custom-codes:
  example:
    commands:
      - "eco give %player% 500"
    message: "&aYou used code 'example'!"
    #In order to use no permission, remove the permission line
    permission: playerreferrals.welcome


minutes-allowed: 60